name: Print Txt file


on:
 workflow_dispatch:




 jobs: 
     print_txt:
      runs-on: ubuntu-latest


      steps:
       - name: Checkout repo
         uses: actions/checkout@v2

       - name: print contents of txt file
         run : |
          cat tanvir.txt
          
            

